name: Deploy Azure API Management

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Validate
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: validate
          name: Development
          scope: resourceGroup
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template-file: ./infra/main.bicep
          resource-group-name: ${{ secrets.AZURE_RESOURCE_GROUP }}
          parameters-file: ./infra/main.parameters.json
          validation-level: providerNoRbac

      - name: What-If
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: whatIf
          name: Development
          scope: resourceGroup
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resource-group-name: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template-file: ./infra/main.bicep
          parameters-file: ./infra/main.parameters.json
          validation-level: providerNoRbac

      - name: Deploy Bicep template
        uses: azure/bicep-deploy@v2
        with:
             type: deployment
             operation: create
             name: Development
             scope: resourceGroup
             subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
             resource-group-name: ${{ secrets.AZURE_RESOURCE_GROUP }}
             template-file: ./infra/main.bicep
             parameters-file: ./infra/main.parameters.json

      - name: Display deployment information
        run: |
          echo "🚀 Deployment completed successfully!"
          echo "Check the Azure portal for your API Management service details"

  validate:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Validate Bicep template
      run: |
        az bicep build --file infra/main.bicep --stdout > /dev/null
        echo "✅ Bicep template validation passed"
